apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: erselekmen/recipe-app-api-app:latest
        ports:
        - containerPort: 8000
